// Code generated by argsgen.
// DO NOT EDIT!
package main

import (
    "errors"
    "flag"
    "fmt"
    "os"
)

func (o *options) flagSet() *flag.FlagSet {
    flagSet := flag.NewFlagSet(os.Args[0], flag.ExitOnError)
    flagSet.StringVar(&o.directory, "directory", o.directory, "directory to serve")
    flagSet.StringVar(&o.directory, "dir", o.directory, "directory to serve")
    flagSet.StringVar(&o.address, "address", o.address, "address to listen")
    flagSet.BoolVar(&o.dev, "dev", o.dev, "run in development mode")
    return flagSet
}

// Parse parses the arguments in os.Args
func (o *options) Parse() error {
    flagSet := o.flagSet()
    args := os.Args[1:]
    for len(args) > 0 {
        if err := flagSet.Parse(args); err != nil {
            return err
        }

        if remaining := flagSet.NArg(); remaining > 0 {
            posIndex := len(args) - remaining
            args = args[posIndex+1:]
            continue
        }
        break
    }

    o.dir = o.directory
    if o.directory == "" {
        return errors.New("argument 'directory' is required")
    }
    if o.dir == "" {
        return errors.New("argument 'dir' is required")
    }
    if o.address == "" {
        return errors.New("argument 'address' is required")
    }
    return nil
}

// MustParse parses the arguments in os.Args or exists on error
func (o *options) MustParse() {
    if err := o.Parse(); err != nil {
        o.flagSet().PrintDefaults()
		fmt.Fprintln(os.Stderr)
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
    }
}
